---
- hosts: localhost
  tasks:
  - name: "Remove jenkins deployment"
    k8s:
      state: absent
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: jenkins

  - name: "Remove jenkins service"
    k8s:
      state: absent
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: jenkins
          namespace: default

  - name: "Remove jenkins-jnlp service"
    k8s:
      state: absent
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: jenkins-jnlp
          namespace: default

  - name: "Remove jenkins persistent volume claim"
    k8s:
      state: absent
      definition:
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: jenkins-pvc
          namespace: default

  - name: "Remove jenkins persistent volume"
    k8s:
      state: absent
      definition:
        apiVersion: v1
        kind: PersistentVolume
        metadata:
          name: jenkins-pv
          namespace: default

  - name: "remove kubernetes python package"
    pip:
      name: kubernetes
      state: absent